thecodeteam/ecs-cf-service-broker

README.md
src/main/java/com/emc/ecs/serviceBroker/service/EcsServiceInstanceBindingService.java
src/main/java/com/emc/ecs/serviceBroker/service/EcsServiceInstanceService.java
src/test/java/com/emc/ecs/serviceBroker/repository/BucketServiceInstanceServiceTest.java

The most recent [Spring Cloud Service Broker](https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker) release candidate introduced a couple of API changes.  The PR updates to the latest API.

Update to latest Spring Cloud Service Broker RC

---

build.gradle

Add [executable options](https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html) for easily starting the broker as a daemon with a PID file.  This will be useful for running as a BOSH release.

Add executable jar opts in gradle build

---

src/main/java/com/emc/ecs/managementClient/Connection.java

If the broker has been running long enough for the ECS client to timeout and reconnect more than three times, the `authRetries` wasn't being reset, so it would stop retrying.  The resets `authRetries` to zero upon a successful login.

Fix for auth timeouts

---

src/main/java/com/emc/ecs/serviceBroker/EcsService.java
src/main/java/com/emc/ecs/serviceBroker/config/Application.java
src/main/java/com/emc/ecs/serviceBroker/repository/ServiceInstanceBindingRepository.java
src/main/java/com/emc/ecs/serviceBroker/repository/ServiceInstanceRepository.java
src/test/java/com/emc/ecs/serviceBroker/repository/BucketServiceInstanceBindingServiceTest.java
src/test/java/com/emc/ecs/serviceBroker/repository/BucketServiceInstanceServiceTest.java

The constructors fire before bean creation, which causes periodic race conditions when a repository action fires before the EcsService is ready.  Resolves #23.

Replace constructors with PostConstruct methods

---

.travis.yml
README.md
build.gradle

These lines (now deleted) in the Gradle config are forcing gradle to run in the production profile, which may not be desired.  The effect of removing this, is that an environment variable, `SPRING_PROFILES_ACTIVE`, is required.

Removes Gradle forcing of spring.profiles.active to production

---

src/main/java/com/emc/ecs/managementClient/model/BaseUrlList.java
src/main/java/com/emc/ecs/managementClient/model/ObjectBucketInfo.java
src/main/java/com/emc/ecs/managementClient/model/UserCreateParam.java
src/main/java/com/emc/ecs/serviceBroker/repository/ServiceInstanceBindingRepository.java
src/main/java/com/emc/ecs/serviceBroker/repository/ServiceInstanceRepository.java

This pull request is focused on resolving occurrences of Sonar rules squid:S1319 - Declarations should use Java collection interfaces such as "List" rather than specific implementation classes such as "LinkedList"
squid:S2039 - Member variable visibility should be specified
You can find more information about the issues here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1319
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2039
Please let me know if you have any questions.
M-Ezzat

Multiple quality improvements

---

src/main/java/com/emc/ecs/managementClient/BucketAction.java
src/main/java/com/emc/ecs/managementClient/ObjectUserAction.java
src/main/java/com/emc/ecs/managementClient/ObjectUserSecretAction.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1192 - String literals should not be duplicated
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1192
Please let me know if you have any questions.
M-Ezzat

squid:S1192 - String literals should not be duplicated

---

src/main/java/com/emc/ecs/managementClient/BaseUrlAction.java
src/main/java/com/emc/ecs/managementClient/BucketAclAction.java
src/main/java/com/emc/ecs/managementClient/BucketAction.java
src/main/java/com/emc/ecs/managementClient/BucketQuotaAction.java
src/main/java/com/emc/ecs/managementClient/ObjectUserAction.java
src/main/java/com/emc/ecs/managementClient/ObjectUserSecretAction.java
src/main/java/com/emc/ecs/managementClient/ReplicationGroupAction.java

This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - Utility classes should not have public constructors
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1118
Please let me know if you have any questions.
M-Ezzat

squid:S1118 - Utility classes should not have public constructors

---

README.md
src/main/java/com/emc/ecs/cloudfoundry/broker/model/ServiceDefinitionProxy.java
src/main/java/com/emc/ecs/cloudfoundry/broker/service/EcsService.java
src/main/java/com/emc/ecs/management/sdk/BucketQuotaAction.java
src/main/java/com/emc/ecs/management/sdk/Connection.java
src/main/java/com/emc/ecs/management/sdk/model/ObjectBucketCreate.java
src/test/java/com/emc/ecs/cloudfoundry/broker/service/EcsServiceInstanceBindingServiceTest.java
src/test/java/com/emc/ecs/cloudfoundry/broker/service/EcsServiceInstanceServiceTest.java
src/test/java/com/emc/ecs/cloudfoundry/broker/service/EcsServiceTest.java
src/test/java/com/emc/ecs/common/Fixtures.java
src/test/java/com/emc/ecs/management/sdk/BucketAclActionTest.java
src/test/java/com/emc/ecs/management/sdk/NamespaceActionTest.java
src/test/java/com/emc/ecs/management/sdk/ReplicationGroupActionTest.java
src/test/resources/application.yml
src/test/resources/mappings/bucket-create-ecs-cf-broker-repository.json
src/test/resources/mappings/bucket-create-testbucket2.json
src/test/resources/mappings/bucket-create-testbucket3.json
src/test/resources/mappings/bucket-create-testbucket4.json

This PR adds bucket encryption, and also nests bucket settings into `service-settings` config block, which allows settings to be specified in service definition, plan or in command-line parameters.  This closes #45.

Add bucket encryption support

---

README.md
src/main/java/com/emc/ecs/cloudfoundry/broker/service/EcsService.java
src/main/java/com/emc/ecs/cloudfoundry/broker/service/EcsServiceInstanceService.java
src/main/java/com/emc/ecs/management/sdk/BucketQuotaAction.java
src/main/resources/application.yml
src/test/java/com/emc/ecs/cloudfoundry/broker/service/EcsServiceInstanceServiceTest.java
src/test/java/com/emc/ecs/cloudfoundry/broker/service/EcsServiceTest.java
src/test/java/com/emc/ecs/common/Fixtures.java
src/test/java/com/emc/ecs/management/sdk/BucketQuotaActionTest.java
src/test/resources/application.yml
src/test/resources/mappings/bucket-delete2-testbucket3.json
src/test/resources/mappings/bucket-quota-info-testbucket3.json
src/test/resources/mappings/bucket-quota-info2-testbucket3.json

Use new service-settings block to configure quota limit & warning.  This also allows catalog creators to set quota settings in either a service or a plan, and allows service-creators the ability to set quotas when there isn't one specified in the service or plan.

New bucket quota settings

---

src/main/resources/application.yml

The default `application.yml` had an incorrect entry in the plans for the quota definition.  The quota format was:
```yaml
quota:
limit:  5
warning: 4
```
It should have been:
```yaml
quota:
limit: 5
warn: 4
```
This closes #65

quota format is "warn" not "warning"

---

README.md
src/main/java/com/emc/ecs/cloudfoundry/broker/config/Application.java
src/main/java/com/emc/ecs/cloudfoundry/broker/config/BrokerConfig.java
src/main/java/com/emc/ecs/cloudfoundry/broker/repository/ServiceInstanceBindingRepository.java
src/main/java/com/emc/ecs/cloudfoundry/broker/repository/ServiceInstanceRepository.java
src/main/java/com/emc/ecs/management/sdk/Connection.java

- removed requirement to provide certificate
- Server Name Indication (SNI) support for object client
- the http client version used in [smart-client-java](https://github.com/EMCECS/smart-client-java/blob/master/build.gradle#L42) is older than `4.3.2` required to support SNI
- `HttpURLConnection` is used for constructing the `S3Client` instead, which supports SNI
- README updates

extended certificate support

---

README.md
build.gradle
src/main/java/com/emc/ecs/cloudfoundry/broker/config/BrokerConfig.java
src/main/java/com/emc/ecs/cloudfoundry/broker/service/BindingWorkflow.java
src/main/java/com/emc/ecs/cloudfoundry/broker/service/BucketBindingWorkflow.java
src/main/java/com/emc/ecs/cloudfoundry/broker/service/EcsServiceInstanceBindingService.java
src/main/java/com/emc/ecs/cloudfoundry/broker/service/NamespaceBindingWorkflow.java
src/main/java/com/emc/ecs/cloudfoundry/broker/service/RemoteConnectBindingWorkflow.java
src/test/java/com/emc/ecs/TestSuite.java
src/test/java/com/emc/ecs/cloudfoundry/broker/service/BucketBindingWorkflowTest.java
src/test/java/com/emc/ecs/cloudfoundry/broker/service/EcsServiceInstanceBindingServiceTest.java
src/test/java/com/emc/ecs/common/Fixtures.java
src/test/resources/wiremockMgmt/mappings/bucket-acl-info-testbucket4.json

This PR includes a handful of fixes:
1. It starts the process of refactoring tests for new workflows with Ginkgo4J (starting with BucketBindingWorkflow)
2. It adds support for host style access for buckets in bindings (rather than path-style access) #79 
3. It fixes a bug when an `object-endpoint` is provided without a port #86 
4. It fixes a sneaky wiremock bug for the ACLs -- I have no idea how this snuck through unit testing...

Improve bindings & fixes

---

build.gradle
charts/templates/application.yaml
charts/templates/broker.yaml
charts/templates/configmap.yaml
charts/templates/deployment.yaml
charts/templates/secrets.yaml
charts/templates/service.yaml
charts/values.yaml
skaffold.yaml
src/main/java/com/emc/ecs/servicebroker/service/BucketBindingWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/EcsService.java

The target branch updates the code to make it compatible with ServiceCatalog however there were still some components missing.  This PR updates the branch with:
1. Java Code Fixes
2. Helm Chart updates to register as a Broker
3. Skaffold configuration to simplify development.
**serviceCatalog Flag**
The `values.yaml` in the chart includes a `serviceCatalog` setting to allow the chart to be installed  against CF or ServiceCatalog with just a single switch.
**Testing**
The branch has been tested on a Kubernetes cluster:
After installation:
```
$ svcat get brokers
NAME                NAMESPACE                           URL                           STATUS
+--------------------------------+-----------+-----------------------------------------------------+--------+
ecs-service-broker-client …
```

Fixes branch to Work as ServiceCatalog Broker

---

Dockerfile

Updates the Dockerfile to be a Multi-Stage docker file that compiles the Java code before creating the final Docker image.
**Testing**
Building:
```
$ docker build --tag broker:pr-test --no-cache .
Sending build context to Docker daemon  52.24MB
Step 1/9 : FROM gradle:4.10-jdk8 as GradleBuilder
---> 8b87b032dac3
Step 2/9 : COPY --chown=gradle:gradle build.gradle /home/gradle/src/build.gradle
---> 41963747ec65
Step 3/9 : COPY --chown=gradle:gradle src /home/gradle/src/src
---> c697d0dbc0aa
Step 4/9 : WORKDIR /home/gradle/src
---> Running in b3f83eb6d103
Removing intermediate container b3f83eb6d103
---> cd0f31e1bcf7
Step 5/9 : ENV GRADLE_USER_HOME=/home/gradle
---> Running in 0f42dfe06bbe
Removing intermediate container 0f42dfe06bbe
---> 8fb4ee6b12cf
Step 6/9 : RUN gradle clean assemble …
```

Add Multi-Stage Docker build

---

Dockerfile

The Dockerfile originally submitted appears to sometimes fail, this updates the Dockerfile to always work.
**Testing**
_Building with NO cache_
```
$ docker build --no-cache .
Sending build context to Docker daemon  59.85MB
Step 1/9 : FROM gradle:4.10-jdk8 as GradleBuilder
---> 8b87b032dac3
Step 2/9 : COPY --chown=gradle:gradle build.gradle /home/gradle/src/ecs-cf-service-broker/build.gradle
---> 3b536087c510
Step 3/9 : COPY --chown=gradle:gradle src /home/gradle/src/ecs-cf-service-broker/src
---> 7c62bde6ea56
Step 4/9 : WORKDIR /home/gradle/src/ecs-cf-service-broker
---> Running in a0255e03cb82
Removing intermediate container a0255e03cb82
---> bd98e3e6060f
Step 5/9 : ENV GRADLE_USER_HOME=/home/gradle
---> Running in 0956b034854f
Removing intermediate container 0956b034854f
---> …
```

Update Dockerfile to correctly build final image

---

build.gradle
charts/templates/configmap.yaml
charts/values.yaml
src/main/java/com/emc/ecs/servicebroker/config/Application.java
src/main/java/com/emc/ecs/servicebroker/config/BrokerConfig.java
src/main/java/com/emc/ecs/servicebroker/model/ReclaimPolicy.java
src/main/java/com/emc/ecs/servicebroker/repository/BucketWipeFactory.java
src/main/java/com/emc/ecs/servicebroker/repository/LastOperationSerializer.java
src/main/java/com/emc/ecs/servicebroker/repository/ServiceInstance.java
src/main/java/com/emc/ecs/servicebroker/service/BucketInstanceWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/EcsService.java
src/main/java/com/emc/ecs/servicebroker/service/EcsServiceInstanceService.java
src/main/java/com/emc/ecs/servicebroker/service/InstanceWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/NamespaceInstanceWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/RemoteConnectionInstanceWorkflow.java
src/test/java/com/emc/ecs/common/Fixtures.java
src/test/java/com/emc/ecs/servicebroker/service/BucketInstanceWorkflowTest.java
src/test/java/com/emc/ecs/servicebroker/service/EcsServiceTest.java
src/test/java/com/emc/ecs/servicebroker/service/ReclaimPolicyTests.java

This PR adds support for the Bucket `ReclaimPolicy` which indicates to the Broker how it should treat a bucket during a delete operation.
The following `ReclaimPolicy` values are supported:
- `Fail` -  (Default) Attempt to delete the bucket but fail if it is not empty
- `Detach` - Do not delete the bucket, instead just delete it from the repository leaving the bucket intact
- `Delete` - Delete all data in the bucket and then delete the bucket
Users indicate the required `ReclaimPolicy` using the `reclaim-policy` parameter during Instance creation.
_Allowed Policies_
Data protection is very important to a lot of users and therefore this PR allows the Services to be configured with a restrictive set of `ReclaimPolicy`.  This is achieve by supplying the `allowed-reclaim-policies` parameter …

Add support for Reclaim Policy and Bucket-Wipe

---

build.gradle
src/main/java/com/emc/ecs/management/sdk/Connection.java
src/main/java/com/emc/ecs/servicebroker/service/EcsService.java
src/main/java/com/emc/ecs/servicebroker/service/EcsServiceInstanceService.java

Fixing an issue occuring in CF:
An attempt was made to call a method that does not exist. The attempt was made from the following location:  
org.glassfish.jersey.message.internal.Statuses$StatusImpl.<init>(Statuses.java:40)  
The following method did not exist:  
javax.ws.rs.core.Response$Status$Family.familyOf(I)Ljavax/ws/rs/core/Response$Status$Family;  
The method's class, javax.ws.rs.core.Response$Status$Family, is available from the following locations:  
jar:file:/home/vcap/app/BOOT-INF/lib/jsr311-api-1.1.1.jar!/javax/ws/rs/core/Response$Status$Family.class  
jar:file:/home/vcap/app/BOOT-INF/lib/jakarta.ws.rs-api-2.1.6.jar!/javax/ws/rs/core/Response$Status$Family.class  
It was loaded from the following location:  
file:/home/vcap/app/BOOT-INF/lib/jsr311-api-1.1.1.jar

Fix classpath issue + additional logging

---

src/main/java/com/emc/ecs/management/sdk/BucketAclAction.java
src/main/java/com/emc/ecs/servicebroker/service/EcsService.java

When `ECSService` is asked to delete artifacts it currently fails if that artifact (namespace, user, bucket) has already been deleted.  This PR tests to see if the requested artifact still exists before initiating the delete request to ECS.

Issue-91 Handle non-existent items when deleting

---

src/main/java/com/emc/ecs/servicebroker/service/EcsService.java
src/test/java/com/emc/ecs/servicebroker/service/EcsServiceTest.java

Fixes the Delete `reclaim-policy` which was broken due to the the prefix being applied twice.  Two new tests have been added to validate that the `wipeAndDeleteBucket` and the `deleteBucket` methods are working correctly.
**Test Results**
*Before Fix:*
```
EcsServiceTest.wipeBucketTest			failed	 41ms
org.junit.ComparisonFailure: 
Expected :ecs-cf-broker-testbucket1
Actual   :ecs-cf-broker-ecs-cf-broker-testbucket1
EcsServiceTest.deleteBucketTest			failed	 4ms
org.junit.ComparisonFailure: 
Expected :ecs-cf-broker-testbucket1
Actual   :ecs-cf-broker-ecs-cf-broker-testbucket1
```
*After Fix*
```
EcsServiceTest.wipeBucketTest          passed     38ms
EcsServiceTest.deleteBucketTest        passed      2ms
```
Broker Logs when deleting bucket `octopus-cb280edc-dd2a-4836-805e-854ce18f1bac`
``` …
```

Issue-155 Fix Delete Reclaim Policy

---

charts/templates/configmap.yaml
src/main/java/com/emc/ecs/servicebroker/repository/ServiceInstance.java
src/main/java/com/emc/ecs/servicebroker/repository/ServiceInstanceBinding.java
src/main/java/com/emc/ecs/servicebroker/service/BindingWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/BindingWorkflowImpl.java
src/main/java/com/emc/ecs/servicebroker/service/BucketBindingWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/BucketInstanceWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/EcsService.java
src/main/java/com/emc/ecs/servicebroker/service/EcsServiceInstanceBindingService.java
src/main/java/com/emc/ecs/servicebroker/service/NamespaceBindingWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/NamespaceInstanceWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/RemoteConnectBindingWorkflow.java
src/test/java/com/emc/ecs/common/Fixtures.java
src/test/java/com/emc/ecs/servicebroker/service/BucketBindingWorkflowTest.java
src/test/java/com/emc/ecs/servicebroker/service/BucketInstanceWorkflowTest.java
src/test/java/com/emc/ecs/servicebroker/service/EcsServiceInstanceBindingServiceTest.java
src/test/java/com/emc/ecs/servicebroker/service/EcsServiceInstanceServiceTest.java
src/test/java/com/emc/ecs/servicebroker/service/EcsServiceTest.java
src/test/java/com/emc/ecs/servicebroker/service/ReclaimPolicyTests.java
src/test/resources/wiremockS3/mappings/s3-delete-binding-cf2f8326-3465-4810-9da1-54d328935b81.json
src/test/resources/wiremockS3/mappings/s3-get-binding-cf2f8326-3465-4810-9da1-54d328935b81.json
src/test/resources/wiremockS3/mappings/s3-put-binding-cf2f8326-3465-4810-9da1-54d328935b81.json

This PR introduces a new parameter called `name` that can be passed with an Instance or Binding Creation to provide a hint to the Broker as to how to name the provisioned artifact (bucket, namespaces, user etc).
If `name` is provided the generated name will be of the format `<prefix>-<name>-<id>` and if the `name` isn't provided the name will be of the format `<prefix>-<id>` as it currently is.  This means the change is backwards compatible and only take effect if a `name` is passed.
**How It Works**
If works by setting the ServiceInstance or ServiceInstanceBinding name correctly during correctly during construction by checking the provided parameters.  
Unfortunately code (and also tests) assumed that the `name` would always be a `SERVICE_INSTANCE_ID` or `BINDING_ID` and took short cuts. …

Issue-120 Provide Control over ECS Artifact Naming

---

src/main/java/com/emc/ecs/servicebroker/service/EcsService.java
src/test/java/com/emc/ecs/common/Fixtures.java
src/test/java/com/emc/ecs/servicebroker/service/EcsServiceTest.java

When creating the BucketQuota for a Bucket with a custom name the code was incorrectly prefixing the bucket ID and NOT the bucket name.  This lead to the Create Quota attempting to create a quota on a bucket that doesn't exist.
This wasn't picked up by the Unit tests previously because `BUCKET_NAME` was used for both the ID and the name of the bucket being created therefore the original Unit tests still produced a valid result even if the prefix was incorrectly applied.  This has been fixed in this PR.

Issue-185 Fixed Bucket Prefix when creating BucketQuota

---

README.md
src/main/java/com/emc/ecs/servicebroker/config/CatalogConfig.java
src/main/java/com/emc/ecs/servicebroker/model/SystemMetadataName.java
src/main/java/com/emc/ecs/servicebroker/service/EcsService.java
src/test/java/com/emc/ecs/common/Fixtures.java
src/test/java/com/emc/ecs/servicebroker/config/CatalogConfigTest.java
src/test/java/com/emc/ecs/servicebroker/service/EcsServiceTest.java
src/test/java/com/emc/ecs/servicebroker/service/MetadataSearchValidationTests.java

Adding support for metadata configuration edited in tile UI. Values are set through additional config variables due to UI framework limitations.

Search Metadata editor in service definition on tile added

---

src/main/java/com/emc/ecs/servicebroker/service/EcsServiceInstanceBindingService.java

Doing same as with missing instance - returning OK response so that an instance could be removed from catalog.

Returning OK when a binding file not found in repo

---

Dockerfile

There is no 6.8 gradle image version.
https://hub.docker.com/_/gradle

GradleBuilder image version up

---

src/main/java/com/emc/ecs/servicebroker/repository/ServiceInstanceBindingRepository.java

ServiceInstanceBindingRepository.find() now returns null if the binding file isn't found - previously it threw an exception which perpetually failed unbind requests

[ECSOE-16667] - unbind requests perpetually fail if binding file is missing
