src/main/java/com/emc/ecs/managementClient/model/BaseUrlInfo.java
src/main/java/com/emc/ecs/serviceBroker/EcsService.java
src/test/java/com/emc/ecs/managementClient/BaseUrlActionTest.java
src/test/resources/mappings/baseurl-info2.json
src/test/resources/mappings/baseurl-list.json

Correct base-url namespace-in-host deserialization

---

src/main/java/com/emc/ecs/serviceBroker/service/EcsServiceInstanceBindingService.java

Add s3Url attribute to credentials

---

README.md
src/main/java/com/emc/ecs/serviceBroker/EcsService.java
src/main/java/com/emc/ecs/serviceBroker/config/Application.java
src/main/java/com/emc/ecs/serviceBroker/config/BrokerConfig.java
src/main/java/com/emc/ecs/serviceBroker/service/EcsServiceInstanceBindingService.java
src/test/java/com/emc/ecs/serviceBroker/repository/ServiceInstanceRepositoryTest.java
src/test/resources/mappings/s3-put-service-inst-bind-one-id.json

Optimize Base URL selection

---

src/main/java/com/emc/ecs/managementClient/Connection.java
src/main/java/com/emc/ecs/serviceBroker/repository/ServiceInstanceBindingRepository.java
src/main/java/com/emc/ecs/serviceBroker/repository/ServiceInstanceRepository.java

This pull request is focused on resolving occurrences of Sonar rule pmd:ImmutableField - Immutable Field
You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=pmd:ImmutableField
Please let me know if you have any questions.
M-Ezzat

pmd:ImmutableField - Immutable Field

---

build.gradle
src/main/java/com/emc/ecs/cloudfoundry/broker/service/EcsService.java
src/main/java/com/emc/ecs/management/sdk/BucketPolicyAction.java
src/main/java/com/emc/ecs/management/sdk/Connection.java
src/main/java/com/emc/ecs/management/sdk/Constants.java
src/main/java/com/emc/ecs/management/sdk/model/BucketPolicy.java
src/main/java/com/emc/ecs/management/sdk/model/BucketPolicyActions.java
src/main/java/com/emc/ecs/management/sdk/model/BucketPolicyEffect.java
src/main/java/com/emc/ecs/management/sdk/model/BucketPolicyPolicy.java
src/main/java/com/emc/ecs/management/sdk/model/BucketPolicyPrincipal.java
src/main/java/com/emc/ecs/management/sdk/model/BucketPolicyResource.java
src/main/java/com/emc/ecs/management/sdk/model/BucketPolicyStatement.java
src/test/java/com/emc/ecs/cloudfoundry/broker/service/BucketBindingWorkflowTest.java
src/test/java/com/emc/ecs/cloudfoundry/broker/service/EcsServiceInstanceBindingServiceTest.java

Gives each binding a default bucket policy that gives wide open access, including ability to create a new bucket policy.
In the case of ACL being applied, least permissive union of ACL and bucket policy is used.

Feature bucket policy

---

build.gradle
src/main/java/com/emc/ecs/cloudfoundry/broker/service/BucketBindingWorkflow.java
src/main/java/com/emc/ecs/cloudfoundry/broker/service/EcsService.java
src/main/java/com/emc/ecs/management/sdk/Connection.java
src/main/java/com/emc/ecs/management/sdk/model/BucketPolicy.java

Default bucket policy is now set with binding parameters
`cf bind-service my-app my-service -c '{"policy": "default-total-access"}'`

Bugfix policy implementation

---

Dockerfile
build.gradle
charts/Chart.yaml
charts/templates/application.yaml
charts/templates/configmap.yaml
charts/templates/deployment.yaml
charts/templates/secrets.yaml
charts/values.yaml
gradle/wrapper/gradle-wrapper.properties
kubernetes/configmap.yaml
kubernetes/pod.yaml
src/main/java/com/emc/ecs/cloudfoundry/broker/config/Application.java
src/main/java/com/emc/ecs/cloudfoundry/broker/config/RestartController.java

New minor release [v1.2.0]
- Kubernetes support and new official docker image
- Helm chart
- `/reset` endpoint to restart Spring Boot app
- bump Spring Boot maintenance release

K8s support, Helm chart, /reset endpoint, version bump

---

src/main/java/com/emc/ecs/servicebroker/service/EcsService.java

Unit tests failed when broker config had null default reclaim policy

Bugfix: unit tests failed

---

src/main/java/com/emc/ecs/servicebroker/service/BindingWorkflowImpl.java
src/main/java/com/emc/ecs/servicebroker/service/BucketBindingWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/NamespaceBindingWorkflow.java
src/test/java/com/emc/ecs/common/Fixtures.java
src/test/java/com/emc/ecs/servicebroker/service/BucketBindingWorkflowTest.java

Enabled url-encoding of S3 access secrets

Issue #130 - URL-escape access key and secret in S3 URL

---

ci/README.md
ci/pipelines/broker-k8s-image-ci/params.yml
ci/pipelines/broker-k8s-image-ci/pipeline.yml
ci/pipelines/broker-k8s-image-release/params.yml
ci/pipelines/broker-k8s-image-release/pipeline.yml
ci/tasks/build-image/task.yml
ci/tasks/generate-tag/task.sh
ci/tasks/generate-tag/task.yml

Added k8s image build pipeline and k8s image release pipeline.

#135 add k8s image build pipelines

---

src/main/java/com/emc/ecs/servicebroker/model/PlanCollectionInstance.java

Added field for a currency code + value in price proxy

#131 - Currency name+value fields in a plan price proxy

---

ci/README.md
ci/pipelines/broker-e2e-SVCAT-testing/README.md
ci/pipelines/broker-e2e-SVCAT-testing/params.yml
ci/pipelines/broker-e2e-SVCAT-testing/pipeline.yml
ci/resources/templates/ServiceBinding.yaml
ci/resources/templates/ServiceInstance.yaml
ci/resources/templates/TestAppPod.yaml
ci/resources/templates/kubeconfig.yml
ci/resources/test-app/Dockerfile
ci/resources/test-app/docker-entrypoint.sh
ci/tasks/compare-values/task.yml
ci/tasks/helm-cmd/task.yml
ci/tasks/kubectl-cmd/task.yml
ci/tasks/wait-until-ready/task.sh
ci/tasks/wait-until-ready/task.yml
ci/tasks/write-file/task.yml

Added pipeline for testing ECS Service broker docker images in k8s cluster.
[Deployed pipeline is here](http://10.52.202.94:8080/teams/main/pipelines/broker-e2e-ci-svcat)

#138 e2e tests with k8s svcat

---

src/main/java/com/emc/ecs/servicebroker/service/EcsService.java
src/test/java/com/emc/ecs/servicebroker/service/EcsServiceTest.java

Fixing unit tests after previous merge (additional existence checks for removed objects)

Issue 91: fix unit tests after merge

---

src/main/java/com/emc/ecs/management/sdk/Connection.java
src/main/java/com/emc/ecs/servicebroker/EcsManagementClientException.java
src/main/java/com/emc/ecs/servicebroker/EcsManagementClientUnauthorizedException.java
src/main/java/com/emc/ecs/servicebroker/EcsManagementResourceNotFoundException.java
src/main/java/com/emc/ecs/servicebroker/config/BrokerConfig.java
src/main/java/com/emc/ecs/servicebroker/model/ServiceDefinitionProxy.java
src/main/java/com/emc/ecs/servicebroker/repository/ServiceInstanceRepository.java
src/main/java/com/emc/ecs/servicebroker/service/BindingWorkflowImpl.java
src/main/java/com/emc/ecs/servicebroker/service/BucketBindingWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/BucketInstanceWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/EcsService.java
src/main/java/com/emc/ecs/servicebroker/service/EcsServiceInstanceBindingService.java
src/main/java/com/emc/ecs/servicebroker/service/EcsServiceInstanceService.java
src/main/java/com/emc/ecs/servicebroker/service/NamespaceBindingWorkflow.java

- 'Use SSL' parameter in broker config
- Minor fixes in namespace binding (use object endpoint value if Base Url is not specified, additional NPE checks)
- Additional configuration checks on startup with better error log messages
- Logging enhancement and cleanup

Preparing 2.0.1 release

---

src/main/java/com/emc/ecs/servicebroker/service/NamespaceBindingWorkflow.java

Bug #172 - no namespace title in binding credentials

Namespace title in binding credentials (#172)

---

src/main/java/com/emc/ecs/servicebroker/service/BucketBindingWorkflow.java
src/main/java/com/emc/ecs/servicebroker/service/EcsService.java
src/main/java/com/emc/ecs/servicebroker/service/NamespaceBindingWorkflow.java
src/test/java/com/emc/ecs/servicebroker/service/BucketBindingWorkflowTest.java

Issue 199 S3 path style access

---

src/main/java/com/emc/ecs/management/sdk/Connection.java
src/main/java/com/emc/ecs/servicebroker/config/CatalogConfig.java
src/main/java/com/emc/ecs/servicebroker/service/EcsService.java
src/main/java/com/emc/ecs/servicebroker/service/s3/S3Service.java

+ better error log message if catalog lacks repository-service definition

Additional s3 initialization logging

---

charts/Chart.yaml
charts/templates/application.yaml
charts/templates/configmap.yaml
charts/values.yaml

- newline removed from configmap
- Use IfNotPresent pull policy and specific image version

Helm chart catalog was empty

---

build.gradle
src/test/resources/application-test.yml

Update log4j dependency to avoid recent vulnerability

Log4shell fix

---

build.gradle

Update spring boot to latest 2.6.x.
Closes #221

Update spring boot version

---

build.gradle

Partially addresses recent SDL scan results.

Updated dependencies to latest versions

---

charts/Chart.yaml
charts/values.yaml

Bump image version in Helm chart

Prepare release 2.3.0

---

src/main/resources/application.yml
src/test/resources/application-test.yml

change spring profile setting in application.yml files due to updated spring library version

Use new spring profile setting in yaml files
